### ISSUE TITLE
Refactor cloudify.nodes.DeploymentProxy node type

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-proxy-plugin#10]
- [x] Create these data types:
```yaml
data_types:
  cloudify.datatypes.Deployment:
    properties:
      outputs:
        required: false
        description: get output ```key``` from deployment proxy and set ```value``` runtime property to the value of the output.
```
- [x] Create a single node type:
```yaml
node_types:
  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        type: boolean
        default: true # this is here for consistency, but really should never be changed.
      resource_id:
        type: string
        required: true
      resource_config:
        type: cloudify.datatypes.Deployment
```
- [x] ```cloudify.nodes.DeploymentProxy``` create operation should wait until the deployment install workflow is in a ```state``` state.
```yaml
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: plugin.tasks.wait_for_state
          inputs:
            state:
              default: 'terminated'
            timeout:
              default: 15
```

**Comment by EarthmanT** [comment]
- [ ] ```cloudify.nodes.DeploymentProxy``` start operation should query the deployments API for the values defined in the resource_config:outputs.key. If ```daemonize``` is true, then start a daemon that queries at an interval of ```interval```. It will set the runtime property defined in resource_config:outputs.value.
```yaml
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: plugin.tasks.query
          inputs:
            daemonize:
              default: false
            interval:
              required: false
            timeout:
              default: 15
```
