### ISSUE TITLE
Example Blueprints

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-proxy-plugin#7]
- [x] Delete ```samples``` directory.
- [x] Create new ```examples``` directory.

**Comment by EarthmanT** [comment]
- [ ] Create a basic blueprint with a single data generating application:
```yaml
node_templates:
  test_app_generates_data:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: scripts/start_generate_data.py
        stop:
          implementation: scripts/stop_generate_data.py
```
- [ ] Write the ```start_generate_data.py``` script. It should start a process and store the pid. It should then generate data every X seconds and store the data in a "data" runtime property.
- [ ] Write the ```stop_generate_data.py``` script. It should kill the process.
- [ ] Write the blueprint outputs to map to the current value of the data generated runtime property.
